---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: read-pod-sa
  namespace: default
  labels:
    app: node-myapp
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pod-cr
  labels:
    app: node-myapp
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pod-crb
  labels:
    app: node-myapp
subjects:
- kind: ServiceAccount
  name: read-pod-sa
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: read-pod-cr
  apiGroup: "rbac.authorization.k8s.io"
